# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ab2366c6c399a6b3fb3c9d7aeec8bc5d6128defc69b10c5943c9c2a1c6dfd14c4a83487c36a6874ce5f07c581ab4264f57db6703f9f8d883e4f190a47337c497

test:
  secret_key_base: 2dce56b8326603f37f4420ea4d31b2f046b5deb3e043fd1e52a8cc7596f75f60da3d582c6a3c01057bb49b107df74b031b13ee1762622b8bf33c9a17d3ed51ad

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
